In [3]:
#Load the data sets

import numpy as np
import pandas as pd
patient=pd.read_csv("Patient_Data.csv")
patient

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [4]:
billing=pd.read_csv("Billing_Data.csv")
billing

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [6]:
#info() 
patient.info()
billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [9]:
# 2 Select relevant columns from billing
billing_columns=patient[['PatientID','Department','Doctor','BillAmount']]
billing_columns

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [12]:
# 3.drop administrative columns

patient=patient.drop(['ReceptionistID','CheckInTime'],axis=1)
patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [14]:
# 4. To find total bill amount per department using groupBy

department_billamount=patient.groupby('Department')['BillAmount'].sum()
department_billamount

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [20]:
#5. Remove duplicate patient records based on PatientID

patient=patient.drop_duplicates(subset='PatientID')
patient                                                        

#---Drop Duplicate means remove the duplicates

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [25]:
#6. Fill missing BillAmount values with the mean bill amount

billAmount_mean=patient['BillAmount'].mean()
billAmount_mean

#remove the null values and replaced them

patient.loc[:,'BillAmount'] = patient['BillAmount'].fillna(billAmount_mean)
patient

#We can replace the values using Fillna() funtcion 
#.loc[] is used to access particular rows and columns in pandas

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [29]:
#7. Merge the billing dataset with patient dataset on PatientID

merge=pd.merge(patient, billing, on = 'PatientID', how='inner')
merge

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [35]:
#8. Concatenate an additional DataFrame that contains new patients for the current week (row-wise)

new_patients=pd.DataFrame({'PatientID':[106,107],
                           'Department':['Cardiology','Oncologist'],
                           'Doctor':['Dr.Paul','Dr.Leo'],
                           'BillAmount':[6000,9000]
                          })
new_patients

#combined
Combined=pd.concat([patient ,new_patients], axis=0)
Combined

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
0        106      NaN   Cardiology    Dr.Paul  6000.000000
1        107      NaN   Oncologist     Dr.Leo  9000.000000

In [39]:
#9. Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise)

new_columns = pd.DataFrame({ 'InsuranceCovered': ['Yes'] * len(patient), 'FinalAmount': patient['BillAmount'] * 0.9 }) 

final= pd.concat( [patient.reset_index(drop='True'), new_columns.reset_index(drop='True')], axis=1 ) 
final

#drop='True' means removes the old index values 
#axis=1 means columns side by side values

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,Yes,4500.0
1,102,Bob,Neurology,Dr. John,6233.333333,Yes,5610.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,Yes,6750.0
3,104,David,Cardiology,Dr. Smith,6200.000000,Yes,5580.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,Yes,5610.0

In [ ]:
Conclusion:
===========

1. dataset was cleaned and analysed successfully.
2. Missing bill amounts weere filled using mean values.
3. Duplicate patient records were removed.
4. Billing and patient datasets were merged successfully.
5. Groupby analysis helped identify department-wise revenue.
6. Concatenation was used to add new patient records and billing columns.